### ISSUE TITLE
What does "Partial" setup mean?

### ISSUE THREAD

**Issue by ej7819** [TDarkShadow/vivanewvegas-wabbajack#13]
Hello, in the most recent release 1.5, in github it's labeled "Partial VNV setup".  I tried looking through the readme.md and the instructions on the wabbajack entry, but couldn't work out if they describe any special instructions needed to make the setup "full."

Would it be helpful for you to add a note or explanation somewhere on why it's a partial setup this time, and whether there's anything in particular we need to do?

**Comment by TDarkShadow** [comment]
True, I haven't really explained why.
The reason is because the manual guide added the steps of decompressing the FNV files, which happens with 2 separate installers.

At the moment, Wabbajack can't do this step automatically due audio conversion and the differences between the Steam and GOG storefront files.
My plan is to code it after the initial release of Wabbajack 3.0 but not sure if I'll be able to.

While I can add a note on how to do it, the step(s) would add to possible user confusion and I'm slowly building off support for the Wabbajack port.
So no, I'm not planning to add instructions on how to make it a full setup.
But I'll see if I can make it a full setup again purely through Wabbajack, later this year.

**Comment by ej7819** [comment]
Ah thanks.  So in the manual guide, this step is for:
" Recompresses the BSAs without zlib compression to increase performances and fixes certain sound effects not playing"

That's the only difference?

**Comment by TDarkShadow** [comment]
And the ESM Master decompressor, yes.
Know that this also requires ini changes so again, that's why I don't recommend it for beginners.

**Comment by ej7819** [comment]
That's fine.  I was only worried that it was necessary to play the modlist.  If it's optional then no probs.  Thanks!
